# Multiple Linear Regression
Here we use linear regression for  a very simple dataset '50_Startups.csv' that contains data of some startup companies and have only 50 entries. The main focus is learning how to do linear regression and that dataset is simple so handling it is easier and doesn't come on the way. Deeper introduction to linear regression can be found from https://towardsdatascience.com/the-complete-guide-to-linear-regression-in-python-3d3f8f06bf8 .

In the linear regression model the  question is to find good coeffients $\beta_0, \beta_1, \beta_2, ..., \beta_n$ such that
$$y = \beta_0 + \beta_1x_1 + \beta_2x_2 + ... + \beta_n x_n $$
describe as well as possible the given data. In our case $x$ variables (so called independent variables) are  R&D Spend, Administration  cost, Marketing Spend and State. The y variable (alias dependant variable) is the profit of the company. This model then gives a possibility to predict $y$ when $x$'s are known.

## Importing the libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

## Importing the dataset

In [2]:
dataset = pd.read_csv('50_Startups.csv')

In [3]:
# Checking data
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   R&D Spend        50 non-null     float64
 1   Administration   50 non-null     float64
 2   Marketing Spend  50 non-null     float64
 3   State            50 non-null     object 
 4   Profit           50 non-null     float64
dtypes: float64(4), object(1)
memory usage: 2.1+ KB


In [4]:
dataset.head()

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

The data looks good. It doesn't have any nan values or any abnormalities.

Nest we separate $x$'s and $y$. So $y$ will be the profit and everything else goes to $X$. We use capital $X$ because it contains more than just one variable. It is actually a matrix of values.

In [3]:
X = dataset.iloc[:,:-1].to_numpy()
y = dataset.iloc[:,-1].to_numpy()

In [7]:
print(X)

[[165349.2 136897.8 471784.1 'New York']
 [162597.7 151377.59 443898.53 'California']
 [153441.51 101145.55 407934.54 'Florida']
 [144372.41 118671.85 383199.62 'New York']
 [142107.34 91391.77 366168.42 'Florida']
 [131876.9 99814.71 362861.36 'New York']
 [134615.46 147198.87 127716.82 'California']
 [130298.13 145530.06 323876.68 'Florida']
 [120542.52 148718.95 311613.29 'New York']
 [123334.88 108679.17 304981.62 'California']
 [101913.08 110594.11 229160.95 'Florida']
 [100671.96 91790.61 249744.55 'California']
 [93863.75 127320.38 249839.44 'Florida']
 [91992.39 135495.07 252664.93 'California']
 [119943.24 156547.42 256512.92 'Florida']
 [114523.61 122616.84 261776.23 'New York']
 [78013.11 121597.55 264346.06 'California']
 [94657.16 145077.58 282574.31 'New York']
 [91749.16 114175.79 294919.57 'Florida']
 [86419.7 153514.11 0.0 'New York']
 [76253.86 113867.3 298664.47 'California']
 [78389.47 153773.43 299737.29 'New York']
 [73994.56 122782.75 303319.26 'Florida']
 [67532

In [8]:
print(y)

[192261.83 191792.06 191050.39 182901.99 166187.94 156991.12 156122.51
 155752.6  152211.77 149759.96 146121.95 144259.4  141585.52 134307.35
 132602.65 129917.04 126992.93 125370.37 124266.9  122776.86 118474.03
 111313.02 110352.25 108733.99 108552.04 107404.34 105733.54 105008.31
 103282.38 101004.64  99937.59  97483.56  97427.84  96778.92  96712.8
  96479.51  90708.19  89949.14  81229.06  81005.76  78239.91  77798.83
  71498.49  69758.98  65200.33  64926.08  49490.75  42559.73  35673.41
  14681.4 ]


## Encoding categorical data
The categorical data has to be coded into a number format, because words don't work as $x$'s in the linear regression model. For this we use a ready made package OneHotEncoder that turns this one caterogical data column to three columns (because initially there are only three state choices in our data) that get numerical value 0 or 1 depending if the entry is from that state what this new column represents. 

In [6]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [3])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [11]:
print(X)

[[0.0 0.0 1.0 165349.2 136897.8 471784.1]
 [1.0 0.0 0.0 162597.7 151377.59 443898.53]
 [0.0 1.0 0.0 153441.51 101145.55 407934.54]
 [0.0 0.0 1.0 144372.41 118671.85 383199.62]
 [0.0 1.0 0.0 142107.34 91391.77 366168.42]
 [0.0 0.0 1.0 131876.9 99814.71 362861.36]
 [1.0 0.0 0.0 134615.46 147198.87 127716.82]
 [0.0 1.0 0.0 130298.13 145530.06 323876.68]
 [0.0 0.0 1.0 120542.52 148718.95 311613.29]
 [1.0 0.0 0.0 123334.88 108679.17 304981.62]
 [0.0 1.0 0.0 101913.08 110594.11 229160.95]
 [1.0 0.0 0.0 100671.96 91790.61 249744.55]
 [0.0 1.0 0.0 93863.75 127320.38 249839.44]
 [1.0 0.0 0.0 91992.39 135495.07 252664.93]
 [0.0 1.0 0.0 119943.24 156547.42 256512.92]
 [0.0 0.0 1.0 114523.61 122616.84 261776.23]
 [1.0 0.0 0.0 78013.11 121597.55 264346.06]
 [0.0 0.0 1.0 94657.16 145077.58 282574.31]
 [0.0 1.0 0.0 91749.16 114175.79 294919.57]
 [0.0 0.0 1.0 86419.7 153514.11 0.0]
 [1.0 0.0 0.0 76253.86 113867.3 298664.47]
 [0.0 0.0 1.0 78389.47 153773.43 299737.29]
 [0.0 1.0 0.0 73994.56 122782.75 3

## Splitting the dataset into the Training set and Test set

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state = 0) 

In [13]:
print(X_test)

[[0.0 1.0 0.0 66051.52 182645.56 118148.2]
 [1.0 0.0 0.0 100671.96 91790.61 249744.55]
 [0.0 1.0 0.0 101913.08 110594.11 229160.95]
 [0.0 1.0 0.0 27892.92 84710.77 164470.71]
 [0.0 1.0 0.0 153441.51 101145.55 407934.54]
 [0.0 0.0 1.0 72107.6 127864.55 353183.81]
 [0.0 0.0 1.0 20229.59 65947.93 185265.1]
 [0.0 0.0 1.0 61136.38 152701.92 88218.23]
 [0.0 1.0 0.0 73994.56 122782.75 303319.26]
 [0.0 1.0 0.0 142107.34 91391.77 366168.42]]


## Training the Multiple Linear Regression model on the Training set
We now do our first linear regression model using skicit-learns LinearRegression package.


In [8]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [11]:
print("Linear regression model is:")
print(f"Profit = {round(regressor.intercept_,3)} + {round(regressor.coef_[0],3)}*California \
+ {round(regressor.coef_[1],3)}*New York + {round(regressor.coef_[2],3)}*Florida \
+ {round(regressor.coef_[3],3)} R&D Spend + {round(regressor.coef_[4],3)}* Administration \
+ {round(regressor.coef_[5],3)}* Marketing Spend")


Linear regression model is:
Profit = 42467.529 + 86.638*California + -872.646*New York + 786.007*Florida + 0.773 R&D Spend + 0.033* Administration + 0.037* Marketing Spend


This is not probably the best possible Linear regression model. First of all because the first three are so called dummy variables and one of them depends on the other two, we can easily remove the one value out of our model. Secondly we should test if all those variables really have a significant effect to our profit. But before we do it let's compare the predicted values and the given values in the test set.


## Predicting the Test set results

In [31]:
y_pred = regressor.predict(X_test)
result_data = np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)), axis = 1)
results = pd.DataFrame(result_data, columns=['Prediction', 'Test set value'])
results['Difference %'] = (results['Prediction']-results['Test set value'])/results['Test set value'] * 100
results

Prediction  Test set value  Difference %
0  103015.201598       103282.38     -0.258687
1  132582.277608       144259.40     -8.094531
2  132447.738452       146121.95     -9.358082
3   71976.098513        77798.83     -7.484343
4  178537.482211       191050.39     -6.549533
5  116161.242302       105008.31     10.621000
6   67851.692097        81229.06    -16.468697
7   98791.733747        97483.56      1.341943
8  113969.435330       110352.25      3.277854
9  167921.065696       166187.94      1.042871

In [34]:
print(f"The average difference is {round(results['Difference %'].mean(),2)} %.")

The average difference is -3.19 %.


Pretty good values we got. Biggest difference between predicted and the given value was about 16 %. And in average the predicted value was only about 3,2 % off.

Next we shall see if we can do this model better by backward elimination. To get better statistics how well our model does we need to use statsmodels package and from there OLS (ordinary least squares) method for calculating the linear regression model.

In [36]:
import statsmodels.api as sm
Xs = sm.add_constant(X_train)
Xs = np.array(Xs, dtype =float)
y_train = np.array(y_train, dtype =float)
model = sm.OLS(y_train,Xs)

In [ ]:
import statsmodels.api as sm
Xs = sm.add_constant(X_train)
Xs = np.array(Xs, dtype =float)
y_train = np.array(y_train, dtype =float)
model = sm.OLS(y_train,Xs)